# Configuración de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dbd_rpg
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración del servidor web
server.port=8080

# Mostrar consultas SQL si es necesario
spring.jdbc.template.query-timeout=30
